# Generated code do not commit.
file(TO_CMAKE_PATH "/root/flutter" FLUTTER_ROOT)
file(TO_CMAKE_PATH "/home/workspace/oldchat_desktop" PROJECT_DIR)

set(FLUTTER_VERSION "1.4.5-beta.5+7" PARENT_SCOPE)
set(FLUTTER_VERSION_MAJOR 1 PARENT_SCOPE)
set(FLUTTER_VERSION_MINOR 4 PARENT_SCOPE)
set(FLUTTER_VERSION_PATCH 5 PARENT_SCOPE)
set(FLUTTER_VERSION_BUILD 7 PARENT_SCOPE)

# Environment variables to pass to tool_backend.sh
list(APPEND FLUTTER_TOOL_ENVIRONMENT
  "FLUTTER_ROOT=/root/flutter"
  "PROJECT_DIR=/home/workspace/oldchat_desktop"
  "DART_DEFINES=RkxVVFRFUl9WRVJTSU9OPTMuNDQuOA==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049MDU4ZTBhZjJjMg==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049MGNkNjEwNzE3Yg==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMi4y"
  "DART_OBFUSCATION=false"
  "TRACK_WIDGET_CREATION=true"
  "TREE_SHAKE_ICONS=false"
  "PACKAGE_CONFIG=/home/workspace/oldchat_desktop/.dart_tool/package_config.json"
  "FLUTTER_TARGET=lib/main.dart"
)
